name: quiz-app
version: "1.0.0"
summary: Quiz App
description: |
  A Quiz application that provides an interactive and engaging quiz experience.
base: core24
confinement: strict
grade: stable

apps:
  quiz-app:
    command: quiz_app
    extensions: [gnome]
    plugs:
      - network
      - home
      - password-manager-service
    desktop: usr/share/applications/quiz-app.desktop

parts:
  quiz-app:
    plugin: flutter
    source: .
    flutter-target: lib/main.dart
    build-packages:
      - lld
      - llvm
    build-environment:
      - PUB_CACHE: "$SNAPCRAFT_PART_BUILD/.pub-cache"

  desktop-file:
    plugin: dump
    source: snap/gui
    organize:
      quiz-app.desktop: usr/share/applications/quiz-app.desktop

  icon:
    plugin: dump
    source: snap/gui
    organize:
      quiz-app.png: usr/share/icons/hicolor/256x256/apps/quiz-app.png

  mimetype-icon:
    plugin: dump
    source: snap/gui
    organize:
      application-x-quiz.png: usr/share/icons/hicolor/256x256/mimetypes/application-x-quiz.png

  mime-info:
    plugin: dump
    source: snap/local
    organize:
      x-quiz.xml: usr/share/mime/packages/x-quiz.xml